# Generated by Django 2.1 on 2018-04-05 21:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeRangeArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('duration', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('durations', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(), blank=True, null=True, size=None)),
            ],
        ),
    ]
